#!/bin/zsh

if [ ! -z "`pgrep offlineimap`" ]
then
	echo "Offlineimap is currently running, exiting"
	exit 1
fi
if [ `pgrep fetch_mail | wc -l` -gt 1 ]
then
	echo "This script is currently running, exiting"
	exit 1
fi

. ~/global
logfile="sync.log"
tmp="fetch.tmp"

[ -d $maildir ] || mkdir -p $maildir
[ -d $maildir/$cpto ] || mkdir -p $maildir/$cpto
:>> $maildir/$logfile
:> $maildir/$tmp

pushd $maildir

print_message "Fetching mail..."
while true
do
	{ offlineimap -qo -u Machine.MachineUI } &> $tmp
	sed -i '/^\/usr\/lib\/python2.6\/site-packages\/offlineimap\// d' $tmp
	sed -i '/self.sslobj = socket.ssl(self.sock,/ d' $tmp
	messages="$(cat $tmp)"
	$(echo $messages >> $logfile)
	if [ "x`echo $messages | grep 'err'`" != "x" ]
	then
		$(echo $messages >> $errorfile)
		print_error "There seems to have been an error."
		echo $messages
		exit 1
	fi
	if [ "x`ls $inbox/new`" != "x" ]
	then
		print_message "    New mail!"
		cp $inbox/new/* $cpto
		mv $inbox/new/* $inbox/cur/
		print_note "Fetching mail..."
	fi
	$(echo "$eightydashes" >> $logfile)
	$(tail -n$savelines $logfile > $tmp)
	$(mv $tmp $logfile)

	sleep 2
done
popd

exit 0
