#!/bin/zsh

if [ ! -z "`pgrep offlineimap`" ]
then
	echo "Offlineimap is currently running, exiting"
	exit 1
fi
if [ `pgrep fetch_mail | wc -l` -gt 1 ]
then
	echo "This script is currently running, exiting"
	exit 1
fi

maildir="Mail"
inbox="GMail/INBOX"
cpto="Fyodor"
logfile="sync.log"

[ -d $maildir ] || mkdir -p $maildir
[ -d $maildir/$cpto ] || mkdir -p $maildir/$cpto
:>> $maildir/$logfile


pushd $maildir
while true
do
	echo "Fetching mail..."
	messages=$(offlineimap -qo -u Machine.MachineUI)
	$(echo $messages >> $logfile)
	if [ "x`echo $messages | grep 'err'`" != "x" ]
	then
		echo "There seems to have been an error."
		echo $messages
		exit 1
	fi
	sleep 2
done
popd

exit 0
