#!/bin/zsh

if [ ! -z "`pgrep offlineimap`" ]
then
	echo "Offlineimap is currently running, exiting"
	exit 1
fi
if [ `pgrep fetch_mail | wc -l` -gt 1 ]
then
	echo "This script is currently running, exiting"
	exit 1
fi

maildir="Mail"
inbox="GMail/INBOX"
cpto="new"
logfile="sync.log"
tmp="tmp"

[ -d $maildir ] || mkdir -p $maildir
[ -d $maildir/$cpto ] || mkdir -p $maildir/$cpto
:>> $maildir/$logfile
:> $maildir/$tmp

pushd $maildir

ctime="$(date +'%y:%m:%d:%H:%M:%S:%N')"
timestamp="[$ctime]"

echo "$timestamp Fetching mail..."
while true
do
	ctime="$(date +'%y:%m:%d:%H:%M:%S:%N')"
	timestamp="[$ctime]"
	{ $(offlineimap -qo -u Machine.MachineUI) } &> $tmp
	sed -i '/^\/usr\/lib\/python2.6\/site-packages\/offlineimap\// d' $tmp
	sed -i '/self.sslobj = socket.ssl(self.sock,/ d' $tmp
	messages="$(cat $tmp)"
	$(echo $messages >> $logfile)
	if [ "x`echo $messages | grep 'err'`" != "x" ]
	then
		echo "$timestamp There seems to have been an error."
		echo $messages
		exit 1
	fi
	if [ "x`ls $inbox/new`" != "x" ]
	then
		echo "$timestamp     New mail!"
		cp $inbox/new/* $cpto
		mv $inbox/new/* $inbox/cur/
		echo "$timestamp Fetching mail..."
	fi
	$(rm $tmp)

	sleep 2
done
popd

exit 0
