#!/bin/zsh

. ~/functions.sh

home="/home/fyodor"
prefix="$home"
maildir="${prefix}/Mail"
inbox="${maildir}/GMail/INBOX"
parsebox="${prefix}/new"
processbox="${prefix}/process"
processed="${prefix}/processed"
errored="${prefix}/errored"
nonexistant="${prefix}/nonexistant"
attachments="${prefix}/attachments"
functions_dir="${prefix}/functions"
logextension=".log"
tmpextension=".tmp"
tendashes="----------"
fortydashes="${tendashes}${tendashes}${tendashes}${tendashes}"
eightydashes="${fortydashes}${fortydashes}"
savelines="1048576"

pushd $home
[ -d $maildir ] 		|| mkdir -p $maildir
[ -d $maildir/$inbox ]	|| mkdir -p $maildir/$inbox
[ -d $parsebox ]		|| mkdir -p $parsebox
[ -d $processbox ]		|| mkdir -p $processbox
[ -d $processed ]		|| mkdir -p $processed
[ -d $errored ] 		|| mkdir -p $errored
[ -d $nonexistant ]		|| mkdir -p $nonexistant
[ -d $attachments ]		|| mkdir -p $attachments

