#!/bin/zsh

txtblk='\e[0;30m' # Black - Regular
txtred='\e[0;31m' # Red
txtgrn='\e[0;32m' # Green
txtylw='\e[0;33m' # Yellow
txtblu='\e[0;34m' # Blue
txtpur='\e[0;35m' # Purple
txtcyn='\e[0;36m' # Cyan
txtwht='\e[0;37m' # White
bldblk='\e[1;30m' # Black - Bold
bldred='\e[1;31m' # Red
bldgrn='\e[1;32m' # Green
bldylw='\e[1;33m' # Yellow
bldblu='\e[1;34m' # Blue
bldpur='\e[1;35m' # Purple
bldcyn='\e[1;36m' # Cyan
bldwht='\e[1;37m' # White
unkblk='\e[4;30m' # Black - Underline
undred='\e[4;31m' # Red
undgrn='\e[4;32m' # Green
undylw='\e[4;33m' # Yellow
undblu='\e[4;34m' # Blue
undpur='\e[4;35m' # Purple
undcyn='\e[4;36m' # Cyan
undwht='\e[4;37m' # White
bakblk='\e[40m'   # Black - Background
bakred='\e[41m'   # Red
badgrn='\e[42m'   # Green
bakylw='\e[43m'   # Yellow
bakblu='\e[44m'   # Blue
bakpur='\e[45m'   # Purple
bakcyn='\e[46m'   # Cyan
bakwht='\e[47m'   # White
txtrst='\e[0m'    # Text Reset

home="/home/fyodor"
maildir="Mail"
inbox="GMail/INBOX"
parsebox="new"
processbox="process"
processed="processed"
logextension=".log"
tendashes="----------"
fortydashes="${tendashes}${tendashes}${tendashes}${tendashes}"
eightydashes="${fortydashes}${fortydashes}"
savelines="1048576"

pushd $home
[ -d $maildir ] 		|| mkdir -p $maildir
[ -d $maildir/$inbox ]	|| mkdir -p $maildir/$inbox
[ -d $parsebox ]		|| mkdir -p $parsebox
[ -d $processbox ]		|| mkdir -p $processbox
[ -d $processed ]		|| mkdir -p $processed

ctime="$(date +'%y:%m:%d:%H:%M:%S:%N')"
timestamp="[$ctime]"

function update_time ()
{
	ctime="$(date +'%y:%m:%d:%H:%M:%S:%N')"
	timestamp="[$ctime]"
}

function message ()
{
	update_time
	echo "${txtgrn}${timestamp}${txtrst} $*"
}

function error ()
{
	update_time
	echo "${txtred}${timestamp}${txtrst} $*"
}

function note ()
{
	update_time
	echo "${txtblu}${timestamp}${txtrst} $*"
}
