#!/bin/zsh

. ~/.config/zsh/functions.zsh

if [ "$UID" -ne "0" ]
then
	print_error "You are not root"
	exit 1
fi

if [ "`pwd`" != "/home/jac/src/multi/fyodor" ]
then
	print_error "Please make sure you're in the right directory,
or this could get sticky."
	exit 1
fi

commit="$(git status | grep "(working directory clean)")"
if [ "x$commit" = "x" ]
then
	print_error "There are things needing to be commited in git."
	exit 1
fi

[ -d fyodor.bak ] || mkdir -p fyodor.bak

dt="`date +'%y.%m.%d.%H.%M.%S.%N'`"
archive="home_fyodor.bak.$dt.tar.gz"
set -A dirs \
	"Mail" "new" "process" "processed"

pushd fyodor
for dir in $dirs
do
	if [ -d "$dir" ]
	then
		print_error "$dir exists in fyodor, but it is something kept \
over from old"
		exit 1
	fi
done
popd

print_note "The date is currently: $dt"

print_message "Tar'ing up /home/fyodor for safe keeping"
[ -d fyodor.bak ] || mkdir -p fyodor.bak
sudo tar -cf "fyodor.bak/$archive" /home/fyodor
if [ ! -f fyodor.bak/$archive ]
then
	print_error "Backup failed, exiting"
	exit 1
fi

mkdir -p fyodor_tmp
for dir in $dirs
do
	print_note "Moving $dir to a temporary safe location"
	mv /home/fyodor/$dir fyodor_tmp
done
print_message "Removing everyithng that was in /home/fyodor"
sudo rm -R /home/fyodor/
print_message "Pushing fyodor to /home"
sudo cp -R fyodor /home
for dir in $dirs
do
	print_note "Moving $dir back into place"
	mv fyodor_tmp/$dir /home/fyodor
done
rmdir fyodor_tmp
print_message "Changing the ownership on /home/fyodor so \
Fyodor can read/write them"
sudo chown -R fyodor:users /home/fyodor
print_note "New version installed!"
