# use the "most" pager if it's available
if [[ -x $(which most) ]]; then
    export PAGER=most
else
    export PAGER=less
fi

# return to w3m when not in X
if [ $DISPLAY ]; then
    export BROWSER="arora"
else
    export BROWSER="lynx"
fi

# more of the same, for editors
if [[ -x $(which vim) ]]; then
    export EDITOR="vim"
else
    export EDITOR="vi"
fi

#	/usr/local/bin \
#for dir in \
#	/opt/java/bin \
#	/usr/share/perl5/vendor_perl/auto/share/dist/Cope \
#	/usr/lib/ccache/bin \
for dir in \
	/home/jac/bin
do
	[ -d "${dir}" ] && PATH="${dir}:${PATH}"
done

# Arch now puts its manpages in here
if [ -d "/usr/share/man" ]; then
    MANPATH="/usr/share/man/:$MANPATH"
fi

# I like a narrow manpage
export MANWIDTH=80

# finally, remove duplicates from paths
typeset -gU path manpath

export XDG_CONFIG_HOME=/home/jac/.config
export LD_PRELOAD=libetc.so
export LIBETC_BLACKLIST=/bin/ls:/bin/mv:/bin/cp:/bin/ln:/bin/rm:/bin/find:/usr/bin/git:/usr/bin/git-upload-pack:/usr/bin/git-cvsserver:/usr/bin/gitk:/usr/bin/git-shell:/usr/bin/git-upload-archive:/usr/bin/git-receive-pack

# options
setopt extended_glob
setopt short_loops
setopt complete_in_word
setopt interactive_comments
#setopt multios
setopt brace_ccl 
#setopt correct 
setopt dvorak 
setopt hash_list_all 
setopt beep 
setopt nomatch
unsetopt notify

# directory stuff
setopt auto_pushd
setopt auto_cd
setopt chase_dots
setopt pushd_ignore_dups
setopt pushd_silent

# history stuff
# I'd love for this to be ten times as big, but this causes history
# searching to slow right down when it can't find anything.
HISTSIZE=10240
SAVEHIST=1048576
HISTFILE=$XDG_CONFIG_HOME/history_zsh
setopt appendhistory
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt hist_reduce_blanks
setopt extended_history
unsetopt hist_no_functions	# double negative?

# The following lines were added by compinstall
#zstyle :compinstall filename '/home/jac/.config/.zshrc'

autoload -Uz compinit; compinit
autoload colors; colors
# End of lines added by compinstall
# End of lines configured by zsh-newuser-install

# easy access to commonly-used directories
hash -d sdb2=/mnt/sdb2	   # external hdd, ext4
hash -d domicile=~/src/d/domicile

if [ -d /etc/rc.d ]; then
    hash -d rc=/etc/rc.d		  # init files (in arch, anyway)
fi

if [ -d /sys/class/ ]; then
    hash -d sys=/sys/class	          # various devices
fi


CONFDIR="$XDG_CONFIG_HOME/zsh"
set -A files \
    "$CONFDIR/aliases.zsh" "$CONFDIR/functions.zsh" \
    "$CONFDIR/style.zsh" "$CONFDIR/keys.zsh" "$CONFDIR/prompt.zsh"

function src()
{
    autoload -U zrecompile
    [ -f "$XDG_CONFIG_HOME/zshrc" ] && zrecompile -p "$XDG_DATA_HOME/zshrc"
    for f in $files; do
		[ -f $f ] && zrecompile -p $f
    done
    source $XDG_CONFIG_HOME/zshrc
}

for f in $files
do
    if [ -f $f ]; then
		source $f
	else
		print "$bg[red]$fg[white]Error:$terminfo[sgr0] $f is unavailable."
    fi
done
