#!/bin/zsh
#&` calculate->calculate
#&` calc->calculate
#&` cal->calculate
#&` bc->calculate
#&` dc->dc

function calculate()
{
	reply "$(echo "$1" | bc)"
}

function dc()
{
	reply "$(echo "$1" | dc)"
}

