#!/bin/zsh
#&` xkcd->xkcd

comic_dir="${prefix}/comics"
[ -d "$comic_dir" ] || mkdir -p $comic_dir

# xkcd
function xkcd() #{{{
{
	pushd $comic_dir
	if [ ! -f "xkcd_$1" ]
	then
		wget -q -O "xkcd.main" "http://www.xkcd.com"
		MAX="$(sed -n 's_.*Permanent link to this comic: http://xkcd.com/\([0-9]\+\)/.*_\1_p' xkcd.main)"
		if [ -z "$1" ]
		then
			requested="$MAX"
		else
			requested="$1"
		fi
		if [ "$requested" -gt "$MAX" ] || [ "$requested" -lt "1" ]
		then
			requested="$(echo "$RANDOM % $MAX + 1" | bc)"
		fi
		wget -q -O "xkcd_$requested" "http://www.xkcd.com/$requested"
		src="$(sed -n '/^<img/ s/.*src="\([^"]*\)".*/\1/p' "xkcd_$requested")"
		title="$(sed -n '/^<img/ s/.*alt="\([^"]*\)".*/\1/p' "xkcd_$requested")"
		alt="$(sed -n '/^<img/ s/.*title="\([^"]*\)".*/\1/p' "xkcd_$requested")"
		wget -q -O "$(basename $src)" "$src"

		echo "src=\"$src\"" > "xkcd_$requested"
		echo "title=\"$title\"" >> "xkcd_$requested"
		echo "alt=\"$alt\"" >> "xkcd_$requested"
	fi

	src="$(sed -n 's/.*src="\([^"]*\)".*/\1/p' "xkcd_$requested")"
	title="$(sed -n 's/.*alt="\([^"]*\)".*/\1/p' "xkcd_$requested")"
	alt="$(sed -n 's/.*title="\([^"]*\)".*/\1/p' "xkcd_$requested")"

	if [ -z "$src" ] || [ -z "$title" ] || [ -z "$alt" ] || [ ! -f "$(basename $src)" ]
	then
		return 1
	fi
	cp "$(basename $src)" $attachments
	MMS "$title
	[$alt]"
	popd
} #}}}

