#!/bin/zsh
#&` [Cc][Oo][Ww]*->cowsay

function cowsay()
{
	cow="$(cowsay $* | sed -n -e '/$[ ]*^/d' \
		-e 's_\\\_\\\\\\\_g' -e 's_.*_& \\\\n_p')"
	convert -background white -fill black -font Inconsolata-Medium \
		-pointsize 18 label:" $cow17" "cowsay.png"
	mv cowsay.png ${attachments}
	MMS
}
