#!/bin/zsh

definition_dir="definitions"

function define() # &`
{
	pushd $definition_dir
	for word in $@
	if [ ! -f "$word" ];
	then
		lynx -dump "http://www.google.com/search?q=define: $word" > "$word"
		cat "$word" | ./def.pl > "${word}.tmp"
		mv "${word}.tmp" "$word"
	fi
	reply="$(cat "$word")"
	popd
}

function def() # &`
{
	define $*
}

function redefine() # &`
{
	pushd $definition_dir
	for arg in $@
	do
		if [ -f "$arg" ]
		then
			rm "$arg"
		fi
	done
	popd
	define $*
}

function rdef() # &`
{
	redefine $*
}

