#!/bin/bash
#&` [Ee][Nn][Gg]*[Jj][Aa][Pp]*->engjap
#&` [Jj][Aa][Pp]*[Ee][Nn][Gg]*->japeng

JAP_DIR="~/${DATA_DIR}/japanese"
[[ -d "${JAP_DIR}" ]] || mkdir -p "${JAP_DIR}"

function translate_japanese()
{
	if [[ -z "$(which convert 2>/dev/null)" ]]; then
		reply "Host system does not have cowsay installed. Bug them."
		return
	fi

	order="eng"
	args="$(echo $* | head -n1)"
	first="$(echo $args | cut -c1)"
	while [[ "$first" = "-" ]]; do
		arg="$(echo $args | cut -f1 -d' ')"
		case "$arg" in
			-[Jj]|--[Jj][Aa][Pp][Aa][Nn][Ee][Ss][Ee])
				order="jap"
				shift
				;;
			-[Ee]|--[Ee][Nn][Gg][Ll][Ii][Ss][Hh])
				order="eng"
				shift
				;;
			*)
				;;
		esac
		args="$(echo $args | cut -f2-999 -d' ')"
		first="$(echo $args | cut -c1)"
	done

	if [ -z "$1" ]
	then
		return
	fi
	if [ "$order" = "eng" ]
	then
		ENG="$1"
		JAP="$2"
	else
		ENG="$2"
		JAP="$1"
	fi

	pushd "${JAP_DIR}"
	if [ ! -f "$1" ]
	then
		JISHO_JAP="http://jisho.org/words?jap="
		JISHO_ENG="&nolimit=1&page=&dict=edict&eng="
		wget -q -U Mozilla -O "${1}.tmp" "${JISHO_JAP}${JAP}${JISHO_ENG}${ENG}"
		sed '1,/<div id="result">/d' "${1}.tmp" |
		grep -E '(class="kanji"|kana_column|meanings_column)' |
		sed -e 's/<[^>]*>//g' > "$1"
		rm "${1}.tmp"
	fi

	total="$(echo "$AMOUNT -1" | bc)"
	AMOUNT="1"
	for i in {0..$total}
	do
		headnum="$(echo "3 + ( $i * 3 )" | bc)"
		japtext="$(head -n$headnum "$1" | tail -n3 |
		head -n2 | sed 's/[ \t]\+/ /g')"
		engtext="$(head -n$headnum "$1" | tail -n1)"
		if [ ! -z "$engtext" ]
		then
			convert -background  white -fill black -font Kochi-Gothic-Regular \
			-pointsize 18 label:"${japtext}" "${1}-${i}.jpg"

			mv "${1}-${i}.jpg" ${attachments}
			MMS "${engtext}"
		fi
		sleep 1
	done

	popd

}

# engjap
function engjap() #{{{
{
	translate_japanese --english "$1"
} #}}}

# japeng
function japeng() #{{{
{
	translate_japanese --japanese "$1"
} #}}}

