#!/bin/bash
#&` [Ww][Ii][Kk][Ii]*->wikipedia
#&` [Rr]*[Ww][Ii][Kk][Ii]*->rewikipedia

WIKI_DIR="~/${DATA_DIR}/wiki"
[[ -d "${WIKI_DIR}" ]] || mkdir -p "${WIKI_DIR}"

# wikipedia
function wikipedia() #{{{
{
	if [[ -z "$1" ]]; then
		return 1
	fi

	pushd "${WIKI_DIR}"
	if [[ ! -f "$1" ]]; then
		WIKI="http://en.wikipedia.org/wiki"
		wget -q -U Mozilla -O "$1" "${WIKI}/$1"
		if [[ -z "$(cat "$1")" ]]; then
			wget -q -U Mozilla -O "$1" "${WIKI}/Special:Search/$1"
		fi
		cat "$1" | sed -n '/<p>/,$ p' |
		lynx --stdin --nolist --dump |
		sed -e '/^Contents/,/^[^ \t]/ {
					/^Contents/! {
						/^[^ \t]/p
						}
					d
					}' -e 's/\[.*\]//g' -e 's/\^//g' > "${1}.tmp"
		if [[ -n "$(grep 'Did you mean: ' "${1}.tmp")" ]]; then
			grep 'Did you mean: ' "${1}.tmp" > "$1"
		else
			cp "${1}.tmp" "${1}"
		fi
		rm "${1}.tmp"
	fi

	if [[ -z "$(cat "$1")" ]]; then
		reply "There was some error in the wiki-ing process. Saving a note so that djef. can look at this page. Sorry for the inconvinience and thanks!"
	fi
	reply "$(cat "$1")"
} #}}}

# rewikipedia
function rewikipedia() #{{{
{
	if [[ -z "$1" ]]; then
		return 1
	fi

	pushd "${WIKI_DIR}"
	rm -f "$1"
	wikipedia "$1"
} #}}}

