#!/bin/zsh

wikipedia_dir="wikipedia"

function wiki()
{
	wikipedia $*
}

function wikipedia()
{
	if [ -z "$1" ]
	then
		exit 1
	fi
	pushd $wikipedia_dir
	if [ ! -f "$1" ]
	then
		wget -q -U Mozilla -O "$1" "http://en.wikipedia.org/wiki/$1"
		cat "$1" | sed -n '/<p>/,$ p' | head -n1 | lynx --stdin --dump
			| sed -e 's/\[[^]]*\]//g' -e 's/\^//g' -e '/^[ \t]*$/,$d' > "${1}.tmp"
		mv "${1}.tmp" "${1}"
	fi
	reply="$(cat "$1")"
	return
}

function rwiki()
{
	rewikipedia $*
}

function rwikipedia()
{
	rewikipedia $*
}

function rewiki()
{
	rewikipedia $*
}

function rewikipedia()
{
	if [ -z "$1" ]
	then
		exit 1
	fi
	if [ -f "$1" ]
	then
		rm "$1"
	fi
	wikipedia "$1"
}

