#!/bin/zsh

wikipedia_dir="wikipedia"
[ -d "$wikipedia_dir" ] || mkdir -p "$wikipedia_dir"

function wiki() # &`
{
	wikipedia $*
}

function wikipedia() # &`
{
	if [ -z "$1" ]
	then
		return 1
	fi
	pushd $wikipedia_dir
	if [ ! -f "$1" ]
	then
		wget -q -U Mozilla -O "$1" "http://en.wikipedia.org/wiki/$1"
		cat "$1" | sed -n '/<p>/,$ p' | lynx --stdin --dump | sed -e 's/\[[^]]*\]//g' -e 's/\^//g' -e '/^[ \t]*$/d' > "${1}.tmp"
		mv "${1}.tmp" "${1}"
	fi
	reply="$(cat "$1")"
	if [ -z "$reply" ]
	then
		reply="There was some error in the wiki-ing process. Saving a note so that djef. can look at this page. Sorry for the inconvinience and thanks!"
	fi
	popd
	return
}

function rwiki() # &`
{
	rewikipedia $*
}

function rwikipedia() # &`
{
	rewikipedia $*
}

function rewiki() # &`
{
	rewikipedia $*
}

function rewikipedia() # &`
{
	if [ -z "$1" ]
	then
		return 1
	fi
	if [ -f "$1" ]
	then
		rm "$1"
	fi
	wikipedia "$1"
}

